# Generated by Django 2.1.7 on 2019-03-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rank',
            table='ranks',
        ),
    ]
